version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - scraper_network

  scraper:
    container_name: scraper
    build: 
      context: ./app  # Dossier pour le backend Flask
      dockerfile: Dockerfile
    networks:
      - scraper_network
    depends_on:
      - mongo
    volumes:
      - ./app:/scraper
    ports:
      - "5001:5001"  # Port pour accéder à votre API

  frontend:
    container_name: frontend
    build:
      context: ./frontend  # Dossier pour le frontend React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Port pour accéder à votre application
    networks:
      - scraper_network

networks:
  scraper_network:
