version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - scraper_network

  scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - scraper_network
    depends_on:
      - mongo
    volumes:
      - ./app:/app  # Assurez-vous que ce chemin est correct

networks:
  scraper_network:
